[package]
name = "dyld-shared-cache-extractor"
version = "0.1.0"
authors = ["Keith Smiley <keithbsmiley@gmail.com>"]
edition = "2018"

[dependencies]
block = "0.1.6"
clap = "3.0.0-beta.2"
libloading = "0.7.0"
